### ISSUE TITLE
只看到build编译，怎么运行程序？

### ISSUE THREAD

**Issue by arden** [blindpirate/gogradle#40]
只看到build编译，怎么运行程序？

**Comment by blindpirate** [comment]
输出文件放在项目目录下的.gogradle文件夹中，以${OS}_${Arch}_${projectName}方式命名，如果是windows下的可执行程序需要加.exe扩展名。

**Comment by arden** [comment]
开发的时候，都希望支持热更新，这个支持吗？

**Comment by blindpirate** [comment]
你说的热更新是什么意思？是希望修改代码后立即反映到输出文件中是么？这个恐怕无法支持，Golang是静态链接的。

**Comment by arden** [comment]
https://beego.me/docs/module/grace.md
像beego这种框架就有热更新的功能。

**Comment by SmallFatCYW** [comment]
@blindpirate 问个题外话。就是应该不止这3个变量吧（就是这种${OS}），第一次用这个东西，能不能告诉我在哪里可以找到全部变量呢？谢谢。。。不是很懂这个，百度的时候关键词全部没get到点。。。

**Comment by blindpirate** [comment]
@SmallFatCYW  [https://golang.org/doc/code.html](https://golang.org/doc/code.html)
@arden 思路很好，不过作为一个构建工具，在完成所有的feature之前，不会对此提供支持
