### ISSUE TITLE
不支持http proxy吗？

### ISSUE THREAD

**Issue by zhangfuwen** [blindpirate/gogradle#45]
公司访问外网都是http proxy，如果能支持一下就好了。

**Comment by blindpirate** [comment]
加参数 `-Dhttp.proxyHost=<host> -Dhttp.proxyPort=<port>` 即可。

**Comment by zhangfuwen** [comment]
明天到公司抽时间试一下，我发帖之前也试过类似的办法。最终都没有成功。

**Comment by zhangfuwen** [comment]
还是不行，代码有SSL的问题，能介绍一下怎么手动下载插件然后使用吗？

**Comment by blindpirate** [comment]
看[这里](https://github.com/blindpirate/gogradle/blob/master/docs/getting-started-cn.md#离线使用gogradle插件)。
