### ISSUE TITLE
Build fails right away with no Go source files in the project directory

### ISSUE THREAD

**Issue by tglaeser** [blindpirate/gogradle#48]
The following project builds fine in native Go but fails right away when building with Gradle.

To reproduce ...
```
$ mkdir -p $GOPATH/src/github.com/tendermint
$ git clone https://github.com/tendermint/tendermint $GOPATH/src/github.com/tendermint/tendermint
$ cd $GOPATH/src/github.com/tendermint/tendermint
$ git checkout develop
$ git pull
$ glide install
$ go install ./cmd/tendermint
$ gradle --no-daemon build
:prepare
Found go 1.8 in C:\opt\go\bin\go.exe, use it.
:resolveBuildDependencies
:installBuildDependencies
:build
can't load package: package .: no buildable Go source files in C:\home\projects\go\src\github.com\tendermint\tendermint
:build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':build'.
> Build failed due to non-zero return code of go process: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
Following my simple Gradle build file ...
```
plugins {
    id 'com.github.blindpirate.gogradle' version '0.2.4'
}

golang {
    packagePath = 'github.com/tendermint/tendermint' // path of project to be built 
}
```
Now, it is true that there are no Go sources directly under directory `$GOPATH/src/github.com/tendermint/tendermint`, but should this fail the build?

Please advise. Thanks.

**Comment by blindpirate** [comment]
Yes, that's expected behavior.

Currently, `gradle build` is equivalent to run `go build -o <outputFile>` with automatically-generated GOPATH in the root directory of project. 

I' still thinking about if it is appropriate to fail the build when no go source file exist in project root. Assume that it's not appropriate, what's your expectations?

**Comment by tglaeser** [comment]
Thanks for the quick response.

I would argue that a clean project layout does not necessarily has to have any sources in the root-project directory, but in the package directories instead.

In this particular case, I believe it makes sense to set the project property `goup` to value `github.com/tendermint/tendermint` and `golang.packagePath` to `./cmd/tendermint`. This would allow to emulate the following Go command ...
```
$ cd $GOPATH/src/github.com/tendermint/tendermint
$ go build ./cmd/tendermint
```
With Gradle being a DSL, that's what I would expect as a user. How can plugin `gogradle` being configured to support this?

Thoughts/ concerns?

**Comment by blindpirate** [comment]
First of all, Gogradle does not conform Golang's GOPATH convention, and it will try to generate a project-scoped GOPATH for each project in project root.

When it comes to the issue we are discussing, I'm considering adding (but haven't implemented yet) `golang.buildTarget` to DSL like this:

```
golang {
    packagePath='github.com/tendermint/tendermint'
    buildTarget='cmd/tendermint'
}
```

Does it make sense?

**Comment by tglaeser** [comment]
Well, this certainly could work, however would not really be in compliance with the _Gradle DSL_.

Here is something you might want to look into however ...

I'm also evaluating Gradle plugin `github.com/echocat/gradle-golang-plugin` which has a similar property `project.golang.packageName` that is equivalent to your property `project.golang.packagePath`. There, no `buildTarget` is needed, it seems to be capable of discovering the sources. It also allows to filter on the sources to be processed via property `project.golang.build.includes`.

Also, one of the key components of the _Gradle DSL_ is a [SourceSet](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html). Shouldn't a Golang plugin support configuration of a `SourceDirectorySet` named `project.sourceSets.main.golang`? Maybe you already do, I just couldn't find this documented anywhere...

**Comment by blindpirate** [comment]
Thanks for your information.

It's my fault to have it failed and I will look into that project to make Gogradle easier to use. However, what I want `golang.buildTarget` to be is similar to `project.golang.build.includes` of `github.com/echocat/gradle-golang-plugin`. 

As for `SourceSet`, I don't think it's necessary to implement it in Golang plugin since Golang's source code structure convention is so different from Java. As said in [SourceSet](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html):

> A SourceSet represents a logical group of **Java** source and resources.

Actually, the `main/java/src` structure convention is derived from [`Maven`](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), and I can't make everyone put their code into `<projectRoot>/src/main/golang`

**Comment by tglaeser** [comment]
You are right that the **physical** layout `src/main/java` was introduced by _Maven_, that was a convention they introduced. The _by-convention_ approach Maven introduced is actually one thing they got right.

However, a `SourceDirectorySet` named `project.sourceSets.main.golang` and `project.sourceSets.test.golang` would be **logical** constructs that can be configured to include sources that don't follow any conventions and it would default to something completely different than `src/main/golang` in the case of _Golang_. Basically, per default, `project.sourceSets.main.golang` could contain all files under the project directory with extension `.go` while `project.sourceSets.test.golang` contains files `*_test.go`.

Please see chapter [Building native software](https://docs.gradle.org/current/userguide/native_software.html) from the Gradle user guide. It seem that the `LanguageSourceSets` there follow a slightly different model, you would have `project.sources.golang` instead of `project.sourceSets.main.golang`.

In the spirit of the _DSL_, you want to follow the same approach for _Golang_ with your Gradle plugin as other plugins do for C, C++, Assembly, etc...

**Comment by blindpirate** [comment]
Thanks.

That's a brilliant advice, I will consider it.

**Comment by tglaeser** [comment]
Cool. Please update the ticket when you have something that I could test. Thanks for the quick turnaround.

**Comment by blindpirate** [comment]
Sure. Thanks.

**Comment by blindpirate** [comment]
@tglaeser I have implement subpackage build in a slightly different way, please see [gogradle/tendermint](https://github.com/gogradle/tendermint) for more details.

**Comment by tglaeser** [comment]
I got a clone of `gogradle/tendermint`, however the tasks fail with the following error ...
```
:resolveBuildDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':resolveBuildDependencies'.
> Cannot resolve dependency:GitNotationDependency{name='gopkg.in/yaml.v2', commit='NEWEST_COMMIT', urls='[https://gopkg.in/yaml.v2]'}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
Please advise.

**Comment by blindpirate** [comment]
Could you rerun it with `--stacktrace` and paste the stack trace of the exception?

**Comment by tglaeser** [comment]
Sure, here is the `Caused by:` part for the exception above ...
```
java.lang.IllegalStateException: Cannot found any files in $GRADLE_USER_HOME/go/gopath/gopkg.in/yaml.v2/.git/refs/heads
        at com.github.blindpirate.gogradle.util.Assert.isTrue(Assert.java:13)
        at com.github.blindpirate.gogradle.util.Assert.isNotEmpty(Assert.java:37)
        at com.github.blindpirate.gogradle.vcs.git.GitClientAccessor.getDefaultBranch(GitClientAccessor.java:65)
        at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.updateRepository(GitMercurialDependencyManager.java:122)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.resolveRepository(AbstractVcsDependencyManager.java:176)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.resolveVcs(AbstractVcsDependencyManager.java:97)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.lambda$doResolve$0(AbstractVcsDependencyManager.java:59)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.runWithGlobalCacheLock(DefaultGlobalCacheManager.java:131)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:57)
```
After purging directory _GRADLE_USER_HOME_/go the build finished successfully.

This triggers couple questions on my side.

1. When building with Go directly, dependencies are cached in directory `vendor` under the project-root directory. Shouldn't Gogradle follow the same pattern?
2. Executing `gradle dependencies` is **significantly** slower compared to executing `glide install ./cmd/tendermint`. This is true not only for the very first run but for subsequent executions as well.

In fact, if I run `glide install ./cmd/tendermint` first and then `gradle dependencies`, the build fails with another exception ...
```
$ gradle dependencies
:prepare
Found go 1.8 in C:\opt\go\bin\go.exe, use it.
:resolveBuildDependencies FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':resolveBuildDependencies'.
> First-level package github.com/davecgh/go-spew conflict!
```
You should be able to reproduce this.

**Comment by blindpirate** [comment]
The answer to the first question is that I can't distinguish `build` and `test` separately. Gogradle will create a directory named `.gogradle` with separated project-scoped `GOPATH` for `build` and `test`. However, `vendor` generation is still supported as described [here](https://github.com/blindpirate/gogradle/blob/master/docs/dependency-management.md#install-dependencies-into-vendor). I have to say I recommend against `vendor` mechanism, which resembles jars in `lib` or `libs` in `ant` era.

The second problem is caused by a bug fixed in `0.4.1`. Now the latest version is `0.4.2` and there are some breaking changes that `gradlew dependencies` is replaced by `gradlew goDependencies` or `gradlew gD`. I have updated [gogradle/tendermint](https://github.com/gogradle/tendermint). Sorry for the inconvenience.

**Comment by tglaeser** [comment]
Thanks Bo. It seems that performance improved quite a bit with version `0.4.2`. I also was able to verify that the previous problems are all resolved. Thanks again for the quick turnaround. Feel free to close the ticket.

If I may, I would like to provide a little more feedback on the recent changes to the plugin, especially the task naming. If you are open to the feedback then please let me know how you would like me to communicate on this with you. Cheers, Thomas

**Comment by blindpirate** [comment]
Sure, thank you for your feedbacks. I have created a chanel named `#gogradle` in `freenode`, please feel free to communicate with me there. BTW, I'm at GMT+8.
