### ISSUE TITLE
Wrong $GOROOT if go binary is not in subpath

### ISSUE THREAD

**Issue by siklol** [blindpirate/gogradle#59]
If the go binary is in i.e. "/usr/bin/go", $GOROOT is automatically set to "/usr" which is wrong.

Solution:
Please add an option to set goroot and go binary by yourself.

**Comment by blindpirate** [comment]
Sure. 

This will be solved in this week's release.

**Comment by siklol** [comment]
Awesome thanks!

**Comment by blindpirate** [comment]
@siklol I guess your `/usr/bin/go` is a symbolic link, can I follow it and resolve to its `../..` as `GOROOT` automatically?

**Comment by siklol** [comment]
`ls -l /usr/bin/ | grep go`
`-rwxr-xr-x 1 root root  6895792 Feb 17 00:28 go`

@blindpirate Nope. Not a symlink. I'm using arch. Also, symlinking it to /usr/lib/go/bin/goExec or somewhere doesn't work either. 
Better to add an option where I can specify the GOROOT

**Comment by blindpirate** [comment]
Got it. Thanks.

**Comment by blindpirate** [comment]
@siklol It has been supported. Please see [configuration](https://github.com/blindpirate/gogradle/blob/master/docs/getting-started.md#configuration) for more details.
