### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by JackTiger** [blindpirate/gogradle#60]
鈹�   鈹溾攢鈹� github.com/magiconair/properties:51463bf 鈭�

./gradlew dependencies显示乱码，有没有比较好的解决方式

**Comment by blindpirate** [comment]
应该是windows的编码问题，等我有空了研究一下

**Comment by JackTiger** [comment]
exception:com.github.blindpirate.gogradle.core.exceptions.BuildException: Build
failed due to return code 1 of cmd: git pull --all --progress
in: C:\Users\xxx\.gradle\go\gopath\xxxx\xxxxx\xxxxxx
stderr: fatal: 'internal' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by JackTiger** [comment]
https://github.com/garyburd/redigo

**Comment by JackTiger** [comment]
C:\Users\xxxx\.gradle\go\gopath\xxxxx\xxxxxx\xxxxx>git pull --all --progress
Fetching internal
fatal: 'internal' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch internal
Fetching origin

C:\Users\xxxx\.gradle\go\gopath\xxxxx\xxxxxx\xxxxx>git pull
Already up-to-date.

**Comment by JackTiger** [comment]
https://github.com/AsynkronIT/protoactor-go

**Comment by JackTiger** [comment]
http://fishedee.com/%E5%90%8E%E7%AB%AF/2016/04/30/golang%E7%BC%96%E8%AF%91%E6%8F%90%E9%80%9F%E4%BC%98%E5%8C%96.html

**Comment by JackTiger** [comment]
Executing task ':resolveBuildDependencies' (up-to-date check took 0.021 secs) du
e to:
  Output property 'installationDirectory' file D:\cell\.gogradle\build_gopath ha
s changed.
  Output property 'installationDirectory' file D:\cell\.gogradle\build_gopath\sr
c has been removed.
  Output property 'installationDirectory' file D:\cell\.gogradle\build_gopath\sr
c\code.huawei.com has been removed.

**Comment by JackTiger** [comment]
我刚试了下，我单独定义了一个任务，执行go test ./...，直接报错了，因为我有个文件依赖(github.com/go-kit/kit/log)是没有添加到dependencies中的，但是我执行gradle.bat test ，就没有报错，好奇怪。

task goTest(type: Go) {
  continueWhenFail = true

  doLast {
    run 'go test ./...'
  }
}

:goTest (Thread[Task worker Thread 3,5,main]) started.
:goTest
Putting task artifact state for task ':goTest' into context took 0.0 secs.
Executing task ':goTest' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
.gogradle\project_gopath\src\xxx\xxxx\xxx\log\log.go:4:2: can
not find package "github.com/go-kit/kit/log" in any of:
        C:\Go\src\github.com\go-kit\kit\log (from $GOROOT)
        D:\cell\.gogradle\project_gopath\src\github.com\go-kit\kit\log (from $GO
PATH)
        D:\cell\.gogradle\build_gopath\src\github.com\go-kit\kit\log
        D:\cell\.gogradle\test_gopath\src\github.com\go-kit\kit\log
:goTest (Thread[Task worker Thread 3,5,main]) completed. Took 1.224 secs.

BUILD SUCCESSFUL

Total time: 3.835 secs


直接执行test任务的log

:test (Thread[Task worker Thread 2,5,main]) started.
:test
Putting task artifact state for task ':test' into context took 0.0 secs.
Executing task ':test' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Test for xxxxxx/xxxxxxx/xxxxxx/log finished, 0 succeed, 0 failed
Test for xxxxxx/xxxxxxx/xxxxxx/hive/template finished, 0 succeed, 0 fa
iled
Generating HTML test report...
Finished generating test html results (0.026 secs) into: D:\cell\.gogradle\repor
ts\test
:test (Thread[Task worker Thread 2,5,main]) completed. Took 5.26 secs.

BUILD SUCCESSFUL

Total time: 2 mins 47.44 secs

**Comment by JackTiger** [comment]
执行 gradlew.bat test -i的部分log

Putting task artifact state for task ':resolveTestDependencies' into context took 0.001 secs.
Task :resolveTestDependencies class loader hash: e15901771d50057dcaf71aa132f4aa6f
Task :resolveTestDependencies actions class loader hash: 123bad7b49d222cc742dd51a7a2101c5
Skipping task ':resolveTestDependencies' as it is up-to-date (took 0.299 secs).
:resolveTestDependencies UP-TO-DATE
:resolveTestDependencies (Thread[Task worker,5,main]) completed. Took 0.305 secs.
:test (Thread[Task worker,5,main]) started.
:test
Putting task artifact state for task ':test' into context took 0.0 secs.
Executing task ':test' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Test for xxxx/xxxx/cell/log finished, 0 succeed, 0 failed
Test for xxxx/xxxx/cell/hive/template finished, 0 succeed, 0 failed
Generating HTML test report...
Finished generating test html results (0.002 secs) into: D:\cell\.gogradle\reports\test
:test (Thread[Task worker,5,main]) completed. Took 1.881 secs.

BUILD SUCCESSFUL

Total time: 4.724 secs

直接执行go test
go test xxxx/xx/cell/log
.gogradle\project_gopath\src\xxxx\xx\cell\log\log.go:4:2: cannot find package "github.com/go-kit/kit/log" in any of:
        C:\Go\src\github.com\go-kit\kit\log (from $GOROOT)
        D:\cell\.gogradle\project_gopath\src\github.com\go-kit\kit\log (from $GOPATH)
        D:\cell\.gogradle\build_gopath\src\github.com\go-kit\kit\log
        D:\cell\.gogradle\test_gopath\src\github.com\go-kit\kit\log

**Comment by JackTiger** [comment]
Caused by: java.lang.IllegalStateException: Cannot found any files in C:/Users/
xxx/.gradle/go/gopath/xxxxx/cell_sample/cell/.git/refs/heads
        at com.github.blindpirate.gogradle.util.Assert.isTrue(Assert.java:13)
        at com.github.blindpirate.gogradle.util.Assert.isNotEmpty(Assert.java:37
)
        at com.github.blindpirate.gogradle.vcs.git.GitClientAccessor.getDefaultB
ranch(GitClientAccessor.java:65)
        at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.updateRepository(GitMercurialDependencyManager.java:122)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDe
pendencyManager.resolveRepository(AbstractVcsDependencyManager.java:176)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDe
pendencyManager.resolveVcs(AbstractVcsDependencyManager.java:97)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDe
pendencyManager.lambda$doResolve$0(AbstractVcsDependencyManager.java:59)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.
runWithGlobalCacheLock(DefaultGlobalCacheManager.java:131)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDe
pendencyManager.doResolve(AbstractVcsDependencyManager.java:57)

**Comment by JackTiger** [comment]
我传递的是git@code.xxx.com:${user}/${project}.git",但是你帮我git clone使用的命令是git clone --recursive -de.xxxx.com/cell_sample/cell.git C:\Users\xxxx\.gradle\go\gopath\code.xxxx.com\cell_sample\cell

log是：

exception:com.github.blindpirate.gogradle.core.exceptions.BuildException: Build
failed due to return code 128 of cmd: git clone --recursive --progress http://co
de.xxxx.com/cell_sample/cell.git C:\Users\xxxxx\.gradle\go\gopath\code.xxxxx
xxx.com\cell_sample\cell
in: D:\progma\Go\src\cell\proc\.
stderr: Cloning into 'C:\Users\l00377907\.gradle\go\gopath\code.xxxxx.com\cell_
sample\cell'...
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'http://code.xxxxxxx.com': Invalid argument
stdout:

**Comment by JackTiger** [comment]
//Defile Project Dependencies
dependencies {
  golang {
    build(nameToPrivateRepo("code.xxxx.com/cell_sample/cell"))
  }
}

def nameToPrivateRepo(String name){
  if(name.startsWith('github.com')){
    def matcher = name=~ /github\.com\/(\w+)\/(\w+)/
    def user = matcher[0][1]
    def project = matcher[0][2]
    return [ name : name, url : "git@code.xxxx.com:${user}/${project}.git" ]
  }
  else if(name.startsWith('code.xxxx.com')){
    def matcher = name=~ /code.xxxx.com\/((?:\w|-)+)\/((?:\w|-)+)/
    //def matcher = name=~ /code.xxxx.com\/(\S+)\/(\S+)\/(\S+)/
    def user = matcher[0][1]
    def project = matcher[0][2]
    return [ name : name, url : "git@code.xxxx.com:${user}/${project}.git" ]
  }
  else{
    return [name:name]
  }
}

**Comment by JackTiger** [comment]
Resolving GitNotationDependency{name='code.xxxx.com/cell_sample/cell', commit='NEWEST_COMMIT', urls='[git@code.xxxx.com:cell_sample/cell.git]'}

**Comment by JackTiger** [comment]
Resolving GitNotationDependency{name='code.xxxx.com/cell_sample/cell', commit='NEWEST_COMMIT', urls='[http://code.xxxx.com/cell_sample/cell.git]'}
Global cache C:\Users\l00377907\.gradle\go\gopath\code.xxxx.com\cell_sample\cell doesn't match url in dependency, it will be cleared.
:resolveBuildDependencies FAILED
:resolveBuildDependencies (Thread[Daemon worker Thread 10,5,main]) completed. Took 3 mins 14.755 secs.

**Comment by JackTiger** [comment]
貌似刚刚遇到的clear没有清除干净，应该也是这个问题导致的，因为URL发生变更了，原来是https，现在变化成http

**Comment by JackTiger** [comment]
---
apiVersion: "0.4.2"
originalUrls:
- "http://code.xxxx.com/cell_sample/cell.git"
lastUpdated:
  time: 1491988630445
  url: "git@code.xxxx.com:cell_sample/cell.git"
originalVcs: "git"

**Comment by JackTiger** [comment]
```
repositories {
  golang {
    root ~ /code.xx.com\/((?:\w|-)+)\/((?:\w|-)+)/
    url { path->
      def split = path.split('/')
      "git@code.xx.com:${split[1]}/${split[2]}.git"
    }
  }
}

dependencies {
  golang {
    build "code.xx.com/cell_sample/cell"
    build "code.xx.com/cell_sample/functionhive"
    build "code.xx.com/cell_sample/servicehive"
  }
}
```

按照说明，这么写，貌似有问题，直接报错
 org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String

**Comment by JackTiger** [comment]
repositories {
  golang {
    root ~/code\.xxxx\.com\/[\w-]+\/[\w-]+/
    url { path->
      def split = path.split('/')
      "git@code.xxxx.com:${split[1]}/${split[2]}.git"
    }
  }
}

//Defile Project Dependencies
dependencies {
  golang {
    build('code.xxx.com/cell_sample/cell')
    build('code.xxx.com/cell_sample/functionhive')
    build('code.xxx.com/cell_sample/servicehive')
  }
}

修改后还是报错：

FAILURE: Build failed with an exception.

* Where:
Script 'D:\progma\Go\src\cell\proc\go.gradle' line: 53

* What went wrong:
A problem occurred evaluating script.
> org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String

报错的点在我定义build依赖的地方

**Comment by JackTiger** [comment]
```
repositories {
  golang {
    root ~/code\.xxxx\.com\/[\w-]+\/[\w-]+/
    url { path->
      def split = path.split('/')
      "git@code.xxxx.com:${split[1]}/${split[2]}.git"
    }
  }
}

//Defile Project Dependencies
dependencies {
  golang {
    build('code.xxx.com/cell_sample/cell')
    build('code.xxx.com/cell_sample/functionhive')
    build('code.xxx.com/cell_sample/servicehive')
  }
}
```

**Comment by JackTiger** [comment]
```
repositories {
  golang {
    root ~/code.xxxx.com\/((?:\w|-)+)\/((?:\w|-)+)/
    url { path->
      def split = path.split('/')
      def splitDomain = split[1]
      def splitDomain2 = split[2]
      println split
      "git@code.xxx.com:${splitDomain}/${splitDomain2}.git"
    }
  }
}

打印出来的结果：[code.xxx.com, cell_sample, cell]

dependencies {
  golang {
    build('code.xxx.com/cell_sample/cell')
  }
}

* What went wrong:
A problem occurred evaluating script.
> org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String

```

**Comment by JackTiger** [comment]
```
排除依赖
dependencies {
    golang {
        build('github.com/a/b') {
            exclude name:'github.com/c/d'
            exclude name:'github.com/c/d', tag: 'v1.0.0'
        }
    }
}

可以写成：

dependencies {
    golang {
        build([name: 'github.com/a/b', version: '2.5'，exclude name:'github.com/c/d',exclude name:'github.com/c/d', ]
    }
}
```

下面这种写法支持吗？

**Comment by JackTiger** [comment]
帮我看一下，我感觉写法没有问题：

```
task test() {
  doLast {
    exec {
      commandLine "set", "PATH=%PATH%;"+"D://progma"
    }
  }
}
```

直接报错，Starting process 'command 'set''. Working directory: D:\progma\Go\src\cell\proc Command: set PATH=%PATH%;D://progma
:test FAILED
:test (Thread[Task worker,5,main]) completed. Took 0.006 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> A problem occurred starting process 'command 'set''
