### ISSUE TITLE
Do not fail if local go installation found

### ISSUE THREAD

**Issue by jonnyzzz** [blindpirate/gogradle#86]
I have the following problem on Windows
```
>gradlew goBuild
:goPrepare
Found go 1.8.1 in C:\go\go-1.8.1\bin\go.exe, use it.
:goPrepare FAILED
```

My goal is to create a cross-platform build for the tool. I expect the build to use it's own Go binaries no matter if there is local go install or not. Currently, the build fail because I have Go locally. This looks like an endless fix&patch process to make the build work. I cannot easily say if all CI machines have or have not the go version. 

Let's have an option (maybe default on) to use sandboxed Go for all builds.

**Comment by blindpirate** [comment]
Actually,  Gogradle will search `go` in `$PATH`, so just execute `./gradlew goBuild` with an empty `PATH` (which can be set via `set` on Windows as well).

**Comment by jonnyzzz** [comment]
I can't change the Path on all machines

**Comment by blindpirate** [comment]
Well, as far as I know, almost all CI server allow user to set environment variables for a build, or at least user can specify them in customized build script such as `export PATH='' && ./gradlew goBuild`, so could you please provide a more specific scenario where this option is indispensable? 

Thanks. :-)

**Comment by jonnyzzz** [comment]
I'm not going to explain that to all team members on how to hack the path
variable. Obviously, path contains other useful tools, e.g. git or docker
which should be there.

This looks as blocker to me now to adopt the plugin in my builds and my
projects.

**Comment by blindpirate** [comment]
I see, I agree with you and would try to add this in next release. Thanks for your advice.

**Comment by blindpirate** [comment]
I suppose this could be closed by the latest release with configuration `goExecutable = 'IGNORE_LOCAL'`. Hope that helps.

**Comment by jonnyzzz** [comment]
Thanks. I'll try that. Could you please update documentation to state that
too

**Comment by blindpirate** [comment]
I have already updated it [here](https://github.com/blindpirate/gogradle/blob/master/docs/getting-started.md#configuration).

**Comment by jonnyzzz** [comment]
Nope, the workaround does not work:
```
> gradlew gobuild
Starting a Gradle Daemon (subsequent builds will be faster)
:goPrepare FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':goPrepare'.
> Failed to run given go executable: IGNORE_LOCAL

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.046 secs```

**Comment by blindpirate** [comment]
Well, I just tried and all goes well. Have you updated Gogradle version to `0.4.9`?

**Comment by jonnyzzz** [comment]
My bad, I was on "0.4.7"

Best regards,
Eugene Petrenko
